# myapp-deployment.yaml 
apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: myapp 
spec:
 replicas: 1
 selector:
   matchLabels:
     app: myapp
 template:
   metadata:
     labels:
       app: myapp
   spec:
     containers:
     - image: supertain147/grpc-server:v1.6
       name: myapp 
       ports:
       - containerPort: 80
