apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "'Content-type: application/json'"
          - "--data"
          - "'{\"text\": \"App Sync succeeded!\"}'"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
