apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "'Content-type: application/json'"
          - "--data"
          - "{\"channel\": \"#认真学习小组\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
